### ISSUE TITLE
0.3.0 still has nil issues

### ISSUE THREAD

**Issue by boodaah3d** [brandonweiss/wow-item-level-overlay#7]
The code for ItemLevelOverlay.lua here on GitHub has been updated.

But on Curseforge and Curse, only the .TOC has updated code. The changes in the LUA weren't put in the newest download.

**Comment by brandonweiss** [comment]
That's odd... how could the .toc have been updated but nothing else?

**Comment by brandonweiss** [comment]
Are you sure? I just downloaded the one from Curse and it has the latest code.

**Comment by boodaah** [comment]
Yes, I just downloaded the one from Curse again. 

ItemLevelOverlay.lua has:

    local function getInventoryItemLevelFromInventorySlotName(inventorySlotName)
      local inventorySlotNumber = select(1, GetInventorySlotInfo(inventorySlotName))
      local inventoryItemLink   = GetInventoryItemLink("player", inventorySlotNumber)
      return ItemUpgradeInfo:GetUpgradedItemLevel(inventoryItemLink)
    end


From GitHub, ItemLevelOverlay.lua:

    local function getInventoryItemLevelFromInventorySlotName(inventorySlotName)
      local inventorySlotNumber = select(1, GetInventorySlotInfo(inventorySlotName))
      local inventoryItemLink   = GetInventoryItemLink("player", inventorySlotNumber)
      if inventoryItemLink then
        return ItemUpgradeInfo:GetUpgradedItemLevel(inventoryItemLink)
      end
    end

**Comment by brandonweiss** [comment]
Crap, I'm an idiot. I didn't pull your changes down after I merged them.

**Comment by brandonweiss** [comment]
K, should be fixed. Sorry about that! You can get the zip from the releases page on GitHub. Curse/forge has it but their system is beyond janky so it can take a little while to propagate.
